import Image from "next/image";

const mission = "Ezra Academics Foundation operates exclusively for charitable and educational purposes by advancing educational equity for low-income and underserved students. The organization provides financial assistance, scholarships, academic support resources, mentorship, and health education initiatives designed to improve academic achievement, support career readiness, and promote long-term socioeconomic mobility.";

const eligibility = [
  ["High School Enrollment", "Currently enrolled in 12th grade at a public high school."],
  ["Residency", "Must live in a low-income or underserved area."],
  ["Financial Need", "Must demonstrate financial hardship, such as free/reduced lunch eligibility or household income verification."],
  ["Personal Statement", "A short paragraph explaining goals, challenges, and how this assistance would help."]
];

export default function AcademicsPage(){return <main>
  <section className="hero academicsHero"><div className="container twoColHero"><div><p className="eyebrow purpleText">Ezra Academics Foundation</p><h1>Advancing educational equity. Supporting brighter futures.</h1><p className="lead">{mission}</p><div className="buttonRow"><a className="button purpleButton" href="https://docs.google.com/forms/d/e/1FAIpQLSc_ttkgBWixIcpIw_vPOhWdKSM5A1YIg-w_1hLFc66nwBX6kg/viewform?pli=1" target="_blank" rel="noreferrer">Request Assistance</a><a className="button buttonGhost" href="mailto:academics@ezrahealth.org">Email the Foundation</a></div></div><div className="heroVisual"><Image src="/images/academics-approved.jpeg" alt="Ezra Health and Academics illustration" width={1100} height={1100} priority /></div></div></section>
  <section className="section"><div className="container contentSplit"><div><p className="eyebrow">President's Message</p><h2>Our mission is personal.</h2></div><div><p>Growing up in a low-income neighborhood with a hardworking mom and a dad who struggled with addiction, I understand what it’s like to face challenges that feel bigger than you. Despite the obstacles, I never let my circumstances define me.</p><p>As the President of this organization, I feel a deep responsibility to give back to the same kind of community that shaped me. I know how tough it can be when money is tight and opportunities seem out of reach—especially during high school. That’s why we’re here: to offer support and financial assistance to students who just need a little help to reach their goals.</p><p>If you or someone you know could use that support, please reach out by email—we’re here for you.</p></div></div></section>
  <section className="section softSection"><div className="container"><div className="sectionIntro centered"><p className="eyebrow purpleText">Senior Send-Off</p><h2>Graduation Expense Assistance Program</h2><p>No senior should miss out on milestone experiences because of finances.</p></div><div className="infoCardGrid"><article className="infoCard"><div className="accentTop purple"/><h3>Assistance may include</h3><p>Yearbook, Grad Night, Prom Night, end-of-year activities, class materials, and college application fees.</p></article><article className="infoCard"><div className="accentTop purple"/><h3>Eligibility</h3><p>Current 12th-grade public high school enrollment, underserved-area residency, documented financial need, and a short personal statement.</p></article><article className="infoCard"><div className="accentTop purple"/><h3>Apply</h3><p>Submit the online form or email the foundation for additional information.</p><a href="https://docs.google.com/forms/d/e/1FAIpQLSc_ttkgBWixIcpIw_vPOhWdKSM5A1YIg-w_1hLFc66nwBX6kg/viewform?pli=1" target="_blank" rel="noreferrer">Open application →</a></article></div></div></section>
  <section className="section"><div className="container"><p className="eyebrow">Eligibility Requirements</p><div className="eligibilityGrid">{eligibility.map(([t,x],i)=><article className="eligibilityCard" key={t}><span>{i+1}</span><h3>{t}</h3><p>{x}</p></article>)}</div><div className="noticeBox"><h3>Proof of income</h3><p>A copy of a parent’s recent pay stub may be requested. The last name, pay period, and amount should remain visible. All other sensitive information must be covered before submission.</p></div><div className="noticeBox"><h3>Interested donors</h3><p>Acceptance of donations is currently pending. During this transition, assistance can still be provided to high school seniors through coordination with our organization and school officials.</p></div></div></section>
</main>}
